### ISSUE TITLE
train.py failed 

### ISSUE THREAD

**Issue by treya-lin** [FinvDialect/2023_finvcup_baseline#1]
Hi, I tried the baseline following the documentation, and encountered an error:

```
2023_finvcup_baseline$ python train.py --loss aamsoftmax --max_epoch 80 --device cuda:0 --save_path ./exps/
train_data_shape: (84623, 3)
valid_data_shape: (21156, 3)
07-12 14:32:47 Model para number = 14.73
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    loss, lr = s.train_network(epoch = epoch, loader = trainLoader)
  File "/home/linyikan/workspace/asr_space/project_space/2023_finvcup_baseline/utils/ECAPAModel.py", line 43, in train_network
    nloss = self.dialect_loss.forward(dialect_embedding, labels)
  File "/home/linyikan/workspace/asr_space/project_space/2023_finvcup_baseline/utils/loss.py", line 47, in forward
    prec1 = accuracy(output.detach(), label.detach(), topk=(1,))[0]
NameError: name 'accuracy' is not defined
```
I looked it up and the function accuracy was not present in any other scripts.

**Comment by treya-lin** [comment]
Tried another command with a different `--loss` and it proceeded fine. Please consider remove that unusable loss from doc or add the implementation of `accuracy` in the code.
